version: "3.6"
services:
  whoami:
    image: emilevauge/whoami
    networks:
      - traefik
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host: test.yuyuko.me"

networks:
  traefik:
    external: true
