version: '2'
services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
    volumes:
    - db-data-kong-postgres:/var/lib/postgresql/data
  kong:
    image: kong:0.9.1
    container_name: kong
    environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    restart: always
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 7946:7946
    - 7946:7946/udp
    links:
    - kong-database
  konga:
    image: pantsel/konga:next
    container_name: konga
    depends_on:
    - kong
    ports:
    - 1337:1337
    links:
    - mongo:db
    - kong:kong
    environment:
    - DB_ADAPTER=mongo
    - DB_HOST=mongo
    - DB_DATABASE=konga
    - NODE_ENV=development
  mongo:
    image: mongo
    volumes:
    - mongo_data:/data/db
    ports:
    - 127.0.0.1:27017:27017
  netdata:
    restart: always
    image: firehol/netdata
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    cap_add:
    - SYS_PTRACE
    security_opt:
    - apparmor=unconfined
    ports:
    - 19999:19999
volumes:
  mongo_data:
  db-data-kong-postgres:
