version: "3.6"
services:
  server:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=9000"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host: admin.awsl.me"

networks:
  traefik:
    external: true

volumes:
  portainer_data:
